[tool]
[tool.poetry]
name = "MytUserbot_Deployer"
version = "1.0"
description = "Automatic Deploy MytUserBot to Heroku"
authors = ["Meyitzade"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
